# Generated by Django 3.1.7 on 2021-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='changed',
        ),
        migrations.AddField(
            model_name='topic',
            name='changed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
